version: '3.7'

services:
  mongodb:
    image: mongo:latest
    volumes:
      - ./init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh:ro
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
      MONGO_INITDB_USERNAME: username
      MONGO_INITDB_PASSWORD: password
      MONGO_INITDB_DATABASE: worlddriven
    ports:
      - 27017:27017
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: worlddriven
      POSTGRES_DB: worlddriven
      POSTGRES_PASSWORD: password
  application:
    build:
      context: .
      dockerfile: development.dockerfile
    command: gunicorn --bind 0.0.0.0:5000 --reload --workers=1 --worker-class=flask_sockets.worker server:app --chdir src
    working_dir: /usr/src/api/
    volumes:
      - ./:/usr/src/api/
    ports:
      - ${PORT:-5000}:5000
    environment:
      - DEBUG=true
      - MONGODB_URI=mongodb://username:password@mongodb:27017/worlddriven
      - PORT=5000
    env_file:
      - .env
    depends_on:
      - mongodb
  frontend:
    image: node:lts
    working_dir: /usr/src/frontend/
    volumes:
      - ./:/usr/src/frontend/
    command: utils/build_frontend.sh
