version: 2
jobs:
    test:
      docker:
        - image: circleci/python:3.7-stretch-node
          environment:
            JAWSDB_MARIA_URL: mysql://worlddriven:password@localhost/worlddriven
        - image: circleci/mariadb:latest
          environment:
            MYSQL_USER: worlddriven
            MYSQL_PASSWORD: password
            MYSQL_DATABASE: worlddriven
      steps:
      - checkout
      - run: sudo pip install -r requirements.txt
      - run: npm install
      - run: npm test
      - run: npm run build
      - run: pycodestyle
      - run: pytest --cov=src --cov-report xml
workflows:
  version: 2
  test_and_deploy:
    jobs:
      - test
